// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import LocationController from "./location_controller.js"
application.register("location", LocationController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import OpeningTimeController from "./opening_time_controller.js"
application.register("opening-time", OpeningTimeController)
