image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: ignore
  # PostgreSQL server
  - port: 5432
    onOpen: ignore
  # Webpack dev server
  - port: 3035
    onOpen: ignore
  # Redis server
  - port: 6379
    onOpen: ignore
  - port: 4444
    onOpen: ignore
  # Headless Chrome (Capybara)
  - port: 9515
    onOpen: ignore

tasks:
  # we run rails db:seed after init, otherwise it can't access the Mapbox API
  - init: >
      bundle install &&
      rails db:create db:schema:load RAILS_ENV=development &&
      rails db:create db:schema:load RAILS_ENV=test &&
      yarn install
    command: rails db:seed

github:
  prebuilds:
    branches: true
    pullRequests: true

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby