image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-browser
  # PostgreSQL server
  - port: 5432
    onOpen: ignore
  # Redis server
  - port: 6379
    onOpen: ignore
  - port: 4444
    onOpen: ignore
  # Headless Chrome (Capybara)
  - port: 9515
    onOpen: ignore

tasks:
  # Start Redis
  - command: redis-server

  # Install dependencies, prepare dev & test databases
  # Seed dev database
  - init: |
      bundle install
      rails db:create db:schema:load RAILS_ENV=development
      rails db:create db:schema:load RAILS_ENV=test
    command: rails db:seed

github:
  prebuilds:
    branches: true
    pullRequests: true

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby