require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - config/**/*
  NewCops: disable

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/**/*

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/NestedGroups:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
   - app/controllers/users/**/*