require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
  NewCops: disable

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - app/helpers/icons_helper.rb

Rails/OutputSafety:
  Exclude:
    - app/helpers/icons_helper.rb

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/**/*

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/NestedGroups:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true

RSpec/ExampleLength:
  Max: 15

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Rails/LexicallyScopedActionFilter:
  Exclude:
   - app/controllers/users/**/*