require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - config/**/*
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

Rails/LexicallyScopedActionFilter:
  Exclude:
   - app/controllers/users/**/*