version: '3.8'

volumes:
  pgdata:

services:
  pg:
    image: postgres:13.2
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
       - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  webpack:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
    ports:
      - '3035:3035'
    environment:
      NODE_ENV: 'development'
      RAILS_ENV: 'development'
      WEBPACKER_DEV_SERVER_HOST: '0.0.0.0'
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    depends_on:
      - pg
      - webpack
    tty: true
    stdin_open: true
