version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  redis:
    image: "redis:alpine"
  sidekiq:
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: ""
    command: bundle exec sidekiq -q default -q mailers
    env_file:
      - .env
  web:
    image: mapzy/mapzy:latest
    entrypoint: ["sh", "/app/docker-entrypoint.sh"]
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env