version: '3.8'
services:
  pg:
    image: postgres:13.2
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports: 
       - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/rails-docker
    ports:
      - "3000:3000"
    depends_on:
      - pg
    tty: true
    stdin_open: true
volumes:
  pgdata: