version: "3.9"
services:
  db:
    image: postgres:16
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["sh", "/app/docker-entrypoint.sh"]
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start -f Procfile.docker.dev"
    tty: true
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env