default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "mapzy_development" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_TEST") { "mapzy_test" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

production:
  <<: *default
  url: <%= ENV["POSTGRES_URL"] %>
