name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: mapzy_test
      RAILS_ENV: test
      NODE_ENV: test

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.17

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --path vendor/bundle --jobs 4 --retry 3
          yarn install

      - name: Setup test database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2

      - name: Run linters
        run: |
          bin/rubocop --parallel

      - name: Run specs
        run: |
          bundle exec rspec spec --color --format progress