name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      POSTGRES_PORT: 5432
      RAILS_ENV: test
      NODE_ENV: test

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install

      - name: Setup test database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run security checks
        run: |
          bundle exec bundle-audit --update
          bundle exec brakeman

      - name: Run linters
        run: |
          bin/rubocop --parallel

      - name: Run specs
        run: |
          bundle exec rspec spec --color --format progress